version: '3.8'

services:
  mongo:
    container_name: ${DB_CONTAINER_NAME}
    image: mongo:7.0-rc
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/mongo/data:/data/db
      - ./data/mongo/logs:/var/log/mongodb
      - ./data/seed:/docker-entrypoint-initdb.d

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    restart: unless-stopped
    command: ['--auth']

  mongo-express:
    container_name: chat_db_panel
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:${DB_PORT}/
    restart: unless-stopped
