version: '3.8'

services:
  mongo:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:7.0-rc
    ports:
      - 27017:27017
    volumes:
      - ./mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    command: ['--auth']
    restart: always

  mongo-express:
    container_name: chat_db_panel
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    restart: always
